### ISSUE TITLE
update any expressions to account for the tag/label change

### ISSUE THREAD

**Issue by adityathebe** [flanksource/mission-control-registry#112]

**Comment by yashmehrotra** [comment]
@moshloop @adityathebe I think this can be closed now, are there any known issues wrt this ?

**Comment by adityathebe** [comment]
@yashmehrotra I think we still have some remains. Eg: [This](https://github.com/flanksource/mission-control-registry/blob/main/charts/mission-control/templates/mission-control.yaml#L473) is still using `tags` whereas it should be using `labels`
