### ISSUE TITLE
Scraper errors

### ISSUE THREAD

**Issue by dabasvibhor** [flanksource/mission-control-registry#89]
failed to get relationships from relationship configs: failed to evaluate relationship config expr: config.status.resources.map(item, { "type": "Kubernetes::" + item.kind, "name": item.name, "labels": { "namespace": item.namespace, }, }).toJSON() : error evaluating expression config.status.resources.map(item, { "type": "Kubernetes::" + item.kind, "name": item.name, "labels": { "namespace": item.namespace, }, }).toJSON() : no such key: namespace: no such key: namespace

**Comment by moshloop** [comment]
@dabasvibhor can you test with using `item.?namespace.orValue(null)`

**Comment by moshloop** [comment]
failed to lookup property PodGroup: error evaluating expression dyn(results).map(r, r.Object).map(r, { 'name': r.metadata.name, 'namespace': r.metadata.namespace, 'type': 'Kubernetes::Pod', 'external_id': r.metadata.namespace + '/' + r.metadata.name, 'parentLookup': {'name': r.metadata.namespace, 'type': 'Kubernetes::Namespace'}, 'labels': k8s.labels(r), 'configs': [{'name': r.metadata.name, 'type': 'Kubernetes::Pod'}], 'logs': [{'name': 'Kubernetes', 'type': 'KubernetesPod'}], 'status': k8s.getHealth(r).health, 'status_reason': k8s.getHealth(r).status + ' ' + k8s.getHealth(r).message, 'properties': [ {"name": "image", "text": r.spec.containers[0].image}, {"name": "cpu", "max": k8s.getResourcesLimit(r, "cpu"), "unit": "millicores", "headline": true}, {"name": "memory", "max": k8s.getResourcesLimit(r, "memory"), "unit": "bytes", "headline": true}, {"name": "node", "text": r.spec.nodeName}, {"name": "created_at", "text": time.Parse('2006-01-02T15:04:05Z07:00', r.metadata.creationTimestamp)}, {"name": "namespace", "text": r.metadata.namespace}, ] }).toJSON() : no such key: nodeName: no such key: nodeName
